name: push

on:
  pull_request:
  push:

jobs:

  compile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 19
          cache: sbt

      - name: Run sbt
        run: sbt -v compile
